In [1]:
# load from drive
from google.colab import drive
drive.mount("/content/drive")

Mounted at /content/drive

In [41]:
import json
from pathlib import Path

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt


data_dir = Path("/content/drive/MyDrive/XFoodRec_Project_Data/raw")
persona_path = data_dir / "personas.json"
recommendation_path = data_dir / "recommendations.json"
recipe_path = data_dir / "recipes.parquet"

In [42]:
with open(persona_path, "r", encoding="utf-8") as f:
    personas = json.load(f)

with open(recommendation_path, "r", encoding="utf-8") as f:
    recommendations = json.load(f)

recipes = pd.read_parquet(recipe_path)

### Inspect source data

In [43]:
print("personas")
print("type:", type(personas))
print("length:", len(personas))

print("\nrecommendations")
print("type:", type(recommendations))
print("length:", len(recommendations))

print("\nrecipes")
print("type:", type(recipes))
print("shape:", recipes.shape)

personas
type: <class 'list'>
length: 40

recommendations
type: <class 'list'>
length: 40

recipes
type: <class 'pandas.core.frame.DataFrame'>
shape: (702, 31)

In [8]:
if isinstance(personas, dict):
    print("persona keys:", personas.keys())
else:
    print("first persona:")
    print(personas[0])

first persona:
{'id': 'user_01', 'description': 'A vegan competitive bodybuilder focused on lean bulking without soy overload.', 'profile': {'age': 28, 'gender': 'Male', 'height': 182.0, 'weight': 84.0, 'activityLevel': 'very_active', 'dietary_goal': 'Muscle Gain', 'dietaryProfile': {'dietaryRestrictions': {'selected': ['Vegan'], 'other': 'High-protein, prefers low-soy options'}, 'foodAllergies': {'selected': [], 'other': ''}, 'healthConditions': {'selected': [], 'other': ''}}, 'likedIngredients': ['Seitan', 'Lentils', 'Chickpeas', 'Hemp seeds'], 'dislikedIngredients': ['Mushrooms', 'Eggplant'], 'favoriteCuisines': ['Middle Eastern', 'Indian', 'Mediterranean']}}

In [9]:
if isinstance(recommendations, dict):
    print("recommendation keys:", recommendations.keys())
else:
    print("first recommendation:")
    print(recommendations[0])

first recommendation:
{'persona': {'id': 'user_01', 'description': 'A vegan competitive bodybuilder focused on lean bulking without soy overload.', 'profile': {'age': 28, 'gender': 'Male', 'height': 182.0, 'weight': 84.0, 'activityLevel': 'very_active', 'dietary_goal': 'Muscle Gain', 'dietaryProfile': {'dietaryRestrictions': {'selected': ['Vegan'], 'other': 'High-protein, prefers low-soy options'}, 'foodAllergies': {'selected': [], 'other': ''}, 'healthConditions': {'selected': [], 'other': ''}}, 'likedIngredients': ['Seitan', 'Lentils', 'Chickpeas', 'Hemp seeds'], 'dislikedIngredients': ['Mushrooms', 'Eggplant'], 'favoriteCuisines': ['Middle Eastern', 'Indian', 'Mediterranean']}}, 'recommendations': [{'recipe_id': '81968', 'title': 'Chickpeas With Spinach (Greek)', 'explanation': 'Chickpeas With Spinach (Greek) is a fantastic choice packed with protein, aligning perfectly with your muscle gain goal. The inclusion of chickpeas and spinach not only satisfies your taste for legumes but also provides essential nutrients for recovery and growth.', 'ingredients': ['onions', 'garlic cloves', 'olive oil', 'cooked chickpeas', 'tomatoes (or same amount', 'red pepper flakes (to taste)', 'paprika', 'oregano', 'package frozen spinach', 'lemon'], 'nutrition': {'calories': 310.2, 'protein': '13.3g', 'carbs': '54.2g', 'fat': '6.2g'}}, {'recipe_id': '10614', 'title': 'Refried Beans', 'explanation': 'Refried Beans offers a high protein content, making it a great option for muscle gain. The use of black beans ensures a hearty meal that aligns with your preferences, while being low in fat.', 'ingredients': ['oil', 'jalapenos', 'onions', '(optional)', 'black beans (or red kidney', 'beer'], 'nutrition': {'calories': 307.1, 'protein': '17.6g', 'carbs': '51.1g', 'fat': '2.6g'}}, {'recipe_id': '94673', 'title': 'Egyptian Red Lentil Soup', 'explanation': 'Egyptian Red Lentil Soup is rich in protein and fiber, ideal for your muscle gain goal. It features lentils, which you enjoy, and provides a warming, nutritious meal that can support your active lifestyle.', 'ingredients': ['vegetable broth', 'red lentils', 'onions', 'potatoes', 'garlic cloves', 'canola oil', 'cumin', 'turmeric', 'salt', 'cilantro', 'lemon juice', 'salt and pepper'], 'nutrition': {'calories': 204.5, 'protein': '10.3g', 'carbs': '35.2g', 'fat': '3.0g'}}, {'recipe_id': '364252', 'title': 'My Favorite Sauteed Kale', 'explanation': 'My Favorite Sauteed Kale is a nutrient-dense option that complements your diet with vitamins and minerals while being low in calories. The olive oil adds healthy fats, making it a balanced side dish for muscle gain.', 'ingredients': ['kale', 'olive oil', 'red pepper flakes', 'garlic cloves', 'vegetable stock', 'salt and pepper', 'balsamic vinegar'], 'nutrition': {'calories': 154.2, 'protein': '5.8g', 'carbs': '18.9g', 'fat': '8.0g'}}, {'recipe_id': '12569', 'title': 'Hearty Black Beans & Rice', 'explanation': 'Hearty Black Beans & Rice combines protein-rich black beans with carbs, perfect for post-workout recovery. This dish aligns well with your preference for legumes and provides a satisfying meal option.', 'ingredients': ['black beans (and liquid)', 'onion', 'cloves garlic', 'tomatoes', 'olive oil', 'balsamic vinegar', 'mild chili powder', 'cumin', 'oregano', 'cinnamon', 'black pepper', 'your favorite hot sauce', 'white rice', 'water', 'oil (optional)'], 'nutrition': {'calories': 533.8, 'protein': '11.4g', 'carbs': '101.5g', 'fat': '11.2g'}}, {'recipe_id': '27778', 'title': 'Black Bean and Corn Salad', 'explanation': "Black Bean and Corn Salad is a colorful, nutritious dish that delivers a good amount of protein and fiber. It's a delightful way to enjoy black beans while also incorporating veggies, supporting your muscle gain goal.", 'ingredients': ['black beans', 'corn', 'tomatoes', 'cilantro', 'red onion', 'lemon juice', 'olive oil', 'salt', 'pepper'], 'nutrition': {'calories': 159.6, 'protein': '6.4g', 'carbs': '23.7g', 'fat': '5.5g'}}, {'recipe_id': '17107', 'title': 'Fried Cabbage', 'explanation': 'Fried Cabbage, while higher in calories, offers a unique flavor profile with a good amount of protein. This dish can be a hearty addition to your meals, fitting well with your preference for vegetables.', 'ingredients': ['bacon', 'onion', 'cabbage', 'red pepper flakes', 'salt', 'black pepper'], 'nutrition': {'calories': 1176.6, 'protein': '32.8g', 'carbs': '33.5g', 'fat': '102.7g'}}, {'recipe_id': '27778', 'title': 'Black Bean and Corn Salad', 'explanation': "Black Bean and Corn Salad is a colorful, nutritious dish that delivers a good amount of protein and fiber. It's a delightful way to enjoy black beans while also incorporating veggies, supporting your muscle gain goal.", 'ingredients': ['black beans', 'corn', 'tomatoes', 'cilantro', 'red onion', 'lemon juice', 'olive oil', 'salt', 'pepper'], 'nutrition': {'calories': 159.6, 'protein': '6.4g', 'carbs': '23.7g', 'fat': '5.5g'}}, {'recipe_id': '11424', 'title': 'Hummus', 'explanation': 'Hummus is a classic, protein-rich dip, perfect as a snack or part of a meal. It pairs well with veggies or whole grains, making it versatile and satisfying for your muscle-building needs.', 'ingredients': ['garbanzo beans', 'tahini (sesame seed paste)', 'lemon juice', 'garlic cloves', 'cumin', 'salt and pepper'], 'nutrition': {'calories': 144.8, 'protein': '5.4g', 'carbs': '19.5g', 'fat': '5.7g'}}, {'recipe_id': '46221', 'title': 'Classic Black Beans and Rice', 'explanation': 'Classic Black Beans and Rice is a traditional dish that combines protein and carbohydrates, making it ideal for muscle gain. This recipe is simple yet fulfilling, aligning with your dietary preferences.', 'ingredients': ['olive oil', 'onion', 'green pepper', 'cloves of garlic', 'black beans (undrained)', 'water', 'oregano', 'sugar', 'package sazon goya (without annato *see note)', 'cooking wine', 'cooked white rice'], 'nutrition': {'calories': 298.4, 'protein': '9.4g', 'carbs': '48.0g', 'fat': '7.4g'}}, {'recipe_id': '12633', 'title': 'Comfort Food Beef Stew', 'explanation': "Comfort Food Beef Stew offers a hearty meal option, though it contains meat, it's rich in protein. While it doesn't align perfectly with your vegan preference, it can be a comforting indulgence.", 'ingredients': ['stew meat', 'flour', 'oil', 'water', 'Worcestershire sauce', 'garlic', 'pepper', 'bay leaves', 'carrots', 'stalks celery', 'red potatoes', 'onions', 'green bell peppers', 'flour', 'water'], 'nutrition': {'calories': 411.3, 'protein': '37.8g', 'carbs': '40.2g', 'fat': '11.8g'}}, {'recipe_id': '46221', 'title': 'Classic Black Beans and Rice', 'explanation': 'Classic Black Beans and Rice is a traditional dish that combines protein and carbohydrates, making it ideal for muscle gain. This recipe is simple yet fulfilling, aligning with your dietary preferences.', 'ingredients': ['olive oil', 'onion', 'green pepper', 'cloves of garlic', 'black beans (undrained)', 'water', 'oregano', 'sugar', 'package sazon goya (without annato *see note)', 'cooking wine', 'cooked white rice'], 'nutrition': {'calories': 298.4, 'protein': '9.4g', 'carbs': '48.0g', 'fat': '7.4g'}}, {'recipe_id': '94673', 'title': 'Egyptian Red Lentil Soup', 'explanation': 'Egyptian Red Lentil Soup is rich in protein and fiber, ideal for your muscle gain goal. It features lentils, which you enjoy, and provides a warming, nutritious meal that can support your active lifestyle.', 'ingredients': ['vegetable broth', 'red lentils', 'onions', 'potatoes', 'garlic cloves', 'canola oil', 'cumin', 'turmeric', 'salt', 'cilantro', 'lemon juice', 'salt and pepper'], 'nutrition': {'calories': 204.5, 'protein': '10.3g', 'carbs': '35.2g', 'fat': '3.0g'}}, {'recipe_id': '364252', 'title': 'My Favorite Sauteed Kale', 'explanation': 'My Favorite Sauteed Kale is a nutrient-dense option that complements your diet with vitamins and minerals while being low in calories. The olive oil adds healthy fats, making it a balanced side dish for muscle gain.', 'ingredients': ['kale', 'olive oil', 'red pepper flakes', 'garlic cloves', 'vegetable stock', 'salt and pepper', 'balsamic vinegar'], 'nutrition': {'calories': 154.2, 'protein': '5.8g', 'carbs': '18.9g', 'fat': '8.0g'}}]}

In [10]:
display(recipes.head())

print("\nrecipe columns:")
print(recipes.columns.tolist())

,recipe_id,title,recipe_url,image_url,ingredients,ingredients_title,tags,calories_per_serving [cal],calories_per_100g [cal],caloriesfromfat_per_serving [cal],...,dietaryfiber_per_serving [g],dietaryfiber_per_100g [g],sugars_per_serving [g],sugars_per_100g [g],protein_per_serving [g],protein_per_100g [g],who_score,fsa_score,nutri_score,health_score
0,113861,My Own Cube Steak and Gravy,https://www.food.com/recipe/my-own-cube-steak-...,https://img.sndimg.com/food/image/upload/f_aut...,"{'': [('cubed steak (4-6 pieces)', '2 time(s)...","[cubed steak (4-6 pieces), oil, butter, flour,...","[Moderate Calorie, Vegetarian]",500.5,175.6,216,...,0.8,0.3,0.8,0.3,48.0,16.8,0.266834,0.250,0.00,3.6
1,111212,Our Secret Sirloin Steak,https://www.food.com/recipe/our-secret-sirloin...,https://img.sndimg.com/food/image/upload/f_aut...,"{'': [('Lea & Perrins Worcestershire Sauce, pl...","[Lea & Perrins Worcestershire Sauce, Lea & Per...","[Moderate Calorie, Vegetarian]",823.6,320.5,502,...,0.4,0.2,3.4,1.3,69.5,27.0,0.186863,0.250,0.00,2.9
2,497021,Mile-High Cabbage Pie #5FIX,https://www.food.com/recipe/mile-high-cabbage-...,https://img.sndimg.com/food/image/upload/f_aut...,"{'': [('lean ground beef', '1 1/2 time(s) lbs ...","[lean beef, coleslaw mix (cabbage and carrots)...",[Moderate Calorie],803.0,221.2,298,...,7.0,1.9,10.7,2.9,48.7,13.4,0.266693,0.250,0.00,3.6
3,31184,15 Minute Shrimp Scampi,https://www.food.com/recipe/15-minute-shrimp-s...,https://img.sndimg.com/food/image/upload/f_aut...,"{'': [('extra virgin olive oil', '0.5 time(s) ...","[extra virgin olive oil, onion, cloves garlic,...",[Moderate Calorie],596.2,342.6,416,...,0.7,0.4,2.2,1.3,26.7,15.3,0.169814,0.250,0.00,2.7
4,71739,Easy Garlic Rice,https://www.food.com/recipe/easy-garlic-rice-7...,https://img.sndimg.com/food/image/upload/f_aut...,"{'': [('olive oil', '2 time(s) tablespoons ')...","[olive oil, onion, garlic cloves, long grain r...",[Moderate Calorie],264.2,190.1,70,...,1.3,0.9,1.6,1.2,6.3,4.5,0.222165,0.625,0.25,5.2

recipe columns:
['recipe_id', 'title', 'recipe_url', 'image_url', 'ingredients', 'ingredients_title', 'tags', 'calories_per_serving [cal]', 'calories_per_100g [cal]', 'caloriesfromfat_per_serving [cal]', 'caloriesfromfat_per_100g [cal]', 'totalfat_per_serving [g]', 'totalfat_per_100g [g]', 'saturatedfat_per_serving [g]', 'saturatedfat_per_100g [g]', 'cholesterol_per_serving [mg]', 'cholesterol_per_100g [mg]', 'sodium_per_serving [mg]', 'sodium_per_100g [mg]', 'totalcarbohydrate_per_serving [g]', 'totalcarbohydrate_per_100g [g]', 'dietaryfiber_per_serving [g]', 'dietaryfiber_per_100g [g]', 'sugars_per_serving [g]', 'sugars_per_100g [g]', 'protein_per_serving [g]', 'protein_per_100g [g]', 'who_score', 'fsa_score', 'nutri_score', 'health_score']

#### Check Persona Data

In [11]:
personas_df = pd.json_normalize(personas)

print(personas_df.shape)
display(personas_df.head())

print(personas_df.columns.tolist())

(40, 17)

,id,description,profile.age,profile.gender,profile.height,profile.weight,profile.activityLevel,profile.dietary_goal,profile.dietaryProfile.dietaryRestrictions.selected,profile.dietaryProfile.dietaryRestrictions.other,profile.dietaryProfile.foodAllergies.selected,profile.dietaryProfile.foodAllergies.other,profile.dietaryProfile.healthConditions.selected,profile.dietaryProfile.healthConditions.other,profile.likedIngredients,profile.dislikedIngredients,profile.favoriteCuisines
0,user_01,A vegan competitive bodybuilder focused on lea...,28,Male,182.0,84.0,very_active,Muscle Gain,[Vegan],"High-protein, prefers low-soy options",[],,[],,"[Seitan, Lentils, Chickpeas, Hemp seeds]","[Mushrooms, Eggplant]","[Middle Eastern, Indian, Mediterranean]"
1,user_02,A type 1 diabetic with a severe tree-nut aller...,34,Female,168.0,67.0,moderately_active,Medical Management,[Low Carb],Counts carbs precisely; prefers low-GI foods,[Tree Nuts],Avoids cross-contamination,[Diabetes (Type 1)],,"[Chicken, Greek yogurt, Broccoli, Berries]","[Sweetened cereals, Fruit juice]","[American, Mediterranean]"
2,user_03,A low-budget student with lactose intolerance ...,20,Non-binary,172.0,92.0,lightly_active,Weight Loss,[Lactose-Free],Very budget-constrained; batch-cooks,[],,[],,"[Rice, Beans, Frozen vegetables, Canned tuna]","[Cottage cheese, Cream sauces]","[Mexican, Asian]"
3,user_04,A pregnant vegetarian with iron-deficiency ane...,31,Female,160.0,64.0,lightly_active,Medical Management,[Vegetarian],"Pregnant; prioritizes iron, folate, choline",[],,[Anemia],Iron-deficiency anemia,"[Eggs, Lentils, Spinach, Fortified cereal]","[Tofu, Beets]","[Mediterranean, Indian]"
4,user_05,A marathon runner with celiac disease optimizi...,26,Male,177.0,66.0,very_active,Energy Boost,[Gluten-Free],Endurance fueling; needs portable snacks,[],,[Celiac Disease],,"[Rice, Potatoes, Bananas, Oats (certified GF)]","[Wheat bread, Barley]","[Japanese, Mexican]"

['id', 'description', 'profile.age', 'profile.gender', 'profile.height', 'profile.weight', 'profile.activityLevel', 'profile.dietary_goal', 'profile.dietaryProfile.dietaryRestrictions.selected', 'profile.dietaryProfile.dietaryRestrictions.other', 'profile.dietaryProfile.foodAllergies.selected', 'profile.dietaryProfile.foodAllergies.other', 'profile.dietaryProfile.healthConditions.selected', 'profile.dietaryProfile.healthConditions.other', 'profile.likedIngredients', 'profile.dislikedIngredients', 'profile.favoriteCuisines']

In [12]:
personas_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 40 entries, 0 to 39
Data columns (total 17 columns):
 #   Column                                               Non-Null Count  Dtype
---  ------                                               --------------  -----
 0   id                                                   40 non-null     object
 1   description                                          40 non-null     object
 2   profile.age                                          40 non-null     int64
 3   profile.gender                                       40 non-null     object
 4   profile.height                                       40 non-null     float64
 5   profile.weight                                       40 non-null     float64
 6   profile.activityLevel                                40 non-null     object
 7   profile.dietary_goal                                 40 non-null     object
 8   profile.dietaryProfile.dietaryRestrictions.selected  40 non-null     object
 9   profile.dietaryProfile.dietaryRestrictions.other     40 non-null     object
 10  profile.dietaryProfile.foodAllergies.selected        40 non-null     object
 11  profile.dietaryProfile.foodAllergies.other           40 non-null     object
 12  profile.dietaryProfile.healthConditions.selected     40 non-null     object
 13  profile.dietaryProfile.healthConditions.other        40 non-null     object
 14  profile.likedIngredients                             40 non-null     object
 15  profile.dislikedIngredients                          40 non-null     object
 16  profile.favoriteCuisines                             40 non-null     object
dtypes: float64(2), int64(1), object(14)
memory usage: 5.4+ KB

In [13]:
personas_df.isna().sum()

id                                                     0
description                                            0
profile.age                                            0
profile.gender                                         0
profile.height                                         0
profile.weight                                         0
profile.activityLevel                                  0
profile.dietary_goal                                   0
profile.dietaryProfile.dietaryRestrictions.selected    0
profile.dietaryProfile.dietaryRestrictions.other       0
profile.dietaryProfile.foodAllergies.selected          0
profile.dietaryProfile.foodAllergies.other             0
profile.dietaryProfile.healthConditions.selected       0
profile.dietaryProfile.healthConditions.other          0
profile.likedIngredients                               0
profile.dislikedIngredients                            0
profile.favoriteCuisines                               0
dtype: int64

In [14]:
print("unique personas:", personas_df["id"].nunique())
print("duplicate ids:", personas_df["id"].duplicated().sum())

unique personas: 40
duplicate ids: 0

In [22]:
distribution_columns = {
    "Gender": "profile.gender",
    "Dietary Goal": "profile.dietary_goal",
    "Activity Level": "profile.activityLevel",
    "Dietary Restriction": "profile.dietaryProfile.dietaryRestrictions.selected",
    "Food Allergy": "profile.dietaryProfile.foodAllergies.selected",
    "Health Condition": "profile.dietaryProfile.healthConditions.selected"
}

persona_distribution = {}

for name, column in distribution_columns.items():
    values = personas_df[column]

    if values.apply(lambda x: isinstance(x, list)).all():
        values = values.explode()

    counts = values.value_counts()
    persona_distribution[name] = pd.Series(
        [f"{category}: {count}" for category, count in counts.items()]
    )

display(pd.DataFrame(persona_distribution).fillna(""))

,Gender,Dietary Goal,Activity Level,Dietary Restriction,Food Allergy,Health Condition
0,Female: 20,Medical Management: 14,lightly_active: 14,High Protein: 3,Tree Nuts: 2,Food Allergy: 2
1,Male: 19,Maintenance: 8,moderately_active: 13,Vegan: 2,Peanuts: 2,Diabetes (Type 1): 1
2,Non-binary: 1,Weight Loss: 7,sedentary: 7,Keto: 2,Milk: 2,Celiac Disease: 1
3,,Energy Boost: 6,very_active: 6,Lactose-Free: 2,Eggs: 2,Post-Surgery: 1
4,,Muscle Gain: 5,,Low Fiber: 2,Shellfish: 1,High Cholesterol: 1
5,,,,Low Sodium: 2,Wheat: 1,Anemia: 1
6,,,,Anti-Inflammatory: 2,Soy: 1,Kidney Disease: 1
7,,,,Low Fat: 2,Sesame: 1,GERD: 1
8,,,,Low Carb: 1,Apples: 1,IBS: 1
9,,,,Vegetarian: 1,,Autism Spectrum: 1
10,,,,Low FODMAP: 1,,PKU: 1
11,,,,Low Acid: 1,,Asthma: 1
12,,,,Pescatarian: 1,,Hypertension: 1
13,,,,Gluten-Free: 1,,ARFID: 1
14,,,,Dairy-Free: 1,,Migraines: 1
15,,,,Low Protein: 1,,EoE: 1
16,,,,No Red Meat: 1,,Gout: 1
17,,,,Halal: 1,,Lupus: 1
18,,,,Jain Vegetarian: 1,,Epilepsy: 1
19,,,,Low Purine: 1,,Histamine Intolerance: 1
20,,,,Elimination Diet: 1,,Gastroparesis: 1
21,,,,Low Histamine: 1,,Rheumatoid Arthritis: 1
22,,,,Kosher: 1,,ADHD: 1
23,,,,Paleo: 1,,Hypothyroidism: 1
24,,,,High Calorie: 1,,Pancreatitis: 1
25,,,,Mediterranean: 1,,Heart Failure: 1
26,,,,,,Ulcerative Colitis: 1
27,,,,,,COPD: 1
28,,,,,,Prediabetes: 1
29,,,,,,Fatty Liver Disease: 1

### Prepare recommendation records

In [44]:
recommendation_rows = []

for item in recommendations:
    persona_id = item["persona"]["id"]

    for rec in item["recommendations"]:
        recommendation_rows.append({
            "persona_id": persona_id,
            **rec
        })

recommendations_df = pd.DataFrame(recommendation_rows)

print(recommendations_df.shape)
display(recommendations_df.head())

(536, 6)

,persona_id,recipe_id,title,explanation,ingredients,nutrition
0,user_01,81968,Chickpeas With Spinach (Greek),Chickpeas With Spinach (Greek) is a fantastic ...,"[onions, garlic cloves, olive oil, cooked chic...","{'calories': 310.2, 'protein': '13.3g', 'carbs..."
1,user_01,10614,Refried Beans,"Refried Beans offers a high protein content, m...","[oil, jalapenos, onions, (optional), black bea...","{'calories': 307.1, 'protein': '17.6g', 'carbs..."
2,user_01,94673,Egyptian Red Lentil Soup,Egyptian Red Lentil Soup is rich in protein an...,"[vegetable broth, red lentils, onions, potatoe...","{'calories': 204.5, 'protein': '10.3g', 'carbs..."
3,user_01,364252,My Favorite Sauteed Kale,My Favorite Sauteed Kale is a nutrient-dense o...,"[kale, olive oil, red pepper flakes, garlic cl...","{'calories': 154.2, 'protein': '5.8g', 'carbs'..."
4,user_01,12569,Hearty Black Beans & Rice,Hearty Black Beans & Rice combines protein-ric...,"[black beans (and liquid), onion, cloves garli...","{'calories': 533.8, 'protein': '11.4g', 'carbs..."

In [24]:
recommendations_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 536 entries, 0 to 535
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   persona_id   536 non-null    object
 1   recipe_id    536 non-null    object
 2   title        536 non-null    object
 3   explanation  536 non-null    object
 4   ingredients  536 non-null    object
 5   nutrition    536 non-null    object
dtypes: object(6)
memory usage: 25.3+ KB

In [25]:
print(recommendations_df.columns.tolist())

['persona_id', 'recipe_id', 'title', 'explanation', 'ingredients', 'nutrition']

In [20]:
personas_df["profile.dietaryProfile.dietaryRestrictions.selected"].explode().value_counts(dropna=False)

profile.dietaryProfile.dietaryRestrictions.selected
NaN                  8
High Protein         3
Vegan                2
Keto                 2
Lactose-Free         2
Low Fiber            2
Low Sodium           2
Anti-Inflammatory    2
Low Fat              2
Low Carb             1
Vegetarian           1
Low FODMAP           1
Low Acid             1
Gluten-Free          1
Pescatarian          1
Dairy-Free           1
Low Protein          1
No Red Meat          1
Halal                1
Jain Vegetarian      1
Low Purine           1
Elimination Diet     1
Low Histamine        1
Kosher               1
Paleo                1
High Calorie         1
Mediterranean        1
Name: count, dtype: int64

In [26]:
rec_counts = recommendations_df.groupby("persona_id").size()

display(rec_counts.describe())

count    40.000000
mean     13.400000
std       1.335895
min      10.000000
25%      12.750000
50%      13.500000
75%      14.000000
max      16.000000
dtype: float64

In [27]:
display(rec_counts.sort_values())

persona_id
user_12    10
user_02    11
user_36    11
user_20    12
user_30    12
user_29    12
user_34    12
user_17    12
user_37    12
user_39    12
user_21    13
user_19    13
user_13    13
user_14    13
user_04    13
user_03    13
user_07    13
user_05    13
user_16    13
user_33    13
user_28    14
user_27    14
user_32    14
user_25    14
user_26    14
user_01    14
user_35    14
user_11    14
user_06    14
user_10    14
user_23    14
user_24    15
user_15    15
user_31    15
user_22    15
user_18    15
user_38    15
user_08    15
user_40    15
user_09    16
dtype: int64

In [28]:
print("total recommendations:", len(recommendations_df))
print("personas:", recommendations_df["persona_id"].nunique())
print("unique recipes:", recommendations_df["recipe_id"].nunique())

total recommendations: 536
personas: 40
unique recipes: 173

In [30]:
duplicate_recs = recommendations_df.duplicated(
    subset=["persona_id", "recipe_id"],
    keep=False
)

print("duplicate recommendation rows:", duplicate_recs.sum())

duplicate recommendation rows: 89

In [31]:
display(
    recommendations_df.loc[
        duplicate_recs,
        ["persona_id", "recipe_id", "title", "explanation"]
    ].sort_values(["persona_id", "recipe_id"])
)

,persona_id,recipe_id,title,explanation
5,user_01,27778,Black Bean and Corn Salad,"Black Bean and Corn Salad is a colorful, nutri..."
7,user_01,27778,Black Bean and Corn Salad,"Black Bean and Corn Salad is a colorful, nutri..."
3,user_01,364252,My Favorite Sauteed Kale,My Favorite Sauteed Kale is a nutrient-dense o...
13,user_01,364252,My Favorite Sauteed Kale,My Favorite Sauteed Kale is a nutrient-dense o...
9,user_01,46221,Classic Black Beans and Rice,Classic Black Beans and Rice is a traditional ...
...,...,...,...,...
431,user_32,8594,Fried Rice,Fried Rice is a versatile dish that can be enj...
460,user_35,30391,Chicken Souvlaki,Chicken Souvlaki is a flavorful option that al...
466,user_35,30391,Chicken Souvlaki,Chicken Souvlaki is a flavorful option that al...
515,user_39,15344,Easy Weeknight Sloppy Joes,Easy Weeknight Sloppy Joes are a hearty option...
520,user_39,15344,Easy Weeknight Sloppy Joes,Easy Weeknight Sloppy Joes are a hearty option...

In [32]:
print(
    "unique persona-recipe pairs:",
    recommendations_df[
        ["persona_id", "recipe_id"]
    ].drop_duplicates().shape[0]
)

unique persona-recipe pairs: 484

### Recipe links

In [33]:
print(recommendations_df["recipe_id"].dtype)
print(recipes["recipe_id"].dtype)

object
int64

In [35]:
recommendations_df["recipe_id"] = recommendations_df["recipe_id"].astype(str)
recipes["recipe_id"] = recipes["recipe_id"].astype(str)

matched = recommendations_df["recipe_id"].isin(recipes["recipe_id"])

print("matched:", matched.sum())
print("unmatched:", (~matched).sum())
print("match rate:", matched.mean())

matched: 536
unmatched: 0
match rate: 1.0

In [36]:
nutrition_df = pd.json_normalize(recommendations_df["nutrition"])

display(nutrition_df.head())

   calories protein   carbs    fat
0     310.2   13.3g   54.2g   6.2g
1     307.1   17.6g   51.1g   2.6g
2     204.5   10.3g   35.2g   3.0g
3     154.2    5.8g   18.9g   8.0g
4     533.8   11.4g  101.5g  11.2g

In [37]:
recommendations_df = pd.concat(
    [
        recommendations_df.drop(columns="nutrition"),
        nutrition_df.add_prefix("rec_")
    ],
    axis=1
)

In [38]:
merged_df = recommendations_df.merge(
    recipes,
    on="recipe_id",
    how="left",
    suffixes=("_rec", "_recipe")
)

print(merged_df.shape)
display(merged_df.head())

(536, 39)

,persona_id,recipe_id,title_rec,explanation,ingredients_rec,rec_calories,rec_protein,rec_carbs,rec_fat,title_recipe,...,dietaryfiber_per_serving [g],dietaryfiber_per_100g [g],sugars_per_serving [g],sugars_per_100g [g],protein_per_serving [g],protein_per_100g [g],who_score,fsa_score,nutri_score,health_score
0,user_01,81968,Chickpeas With Spinach (Greek),Chickpeas With Spinach (Greek) is a fantastic ...,"[onions, garlic cloves, olive oil, cooked chic...",310.2,13.3g,54.2g,6.2g,Chickpeas With Spinach (Greek),...,12.6,3.1,5.1,1.3,13.3,3.3,0.275309,0.75,0.50,6.9
1,user_01,10614,Refried Beans,"Refried Beans offers a high protein content, m...","[oil, jalapenos, onions, (optional), black bea...",307.1,17.6g,51.1g,2.6g,Refried Beans,...,17.4,7.9,1.8,0.8,17.6,8.0,0.349709,1.00,1.00,10.0
2,user_01,94673,Egyptian Red Lentil Soup,Egyptian Red Lentil Soup is rich in protein an...,"[vegetable broth, red lentils, onions, potatoe...",204.5,10.3g,35.2g,3.0g,Egyptian Red Lentil Soup,...,12.0,10.6,3.6,3.2,10.3,9.1,0.261062,0.75,0.50,6.8
3,user_01,364252,My Favorite Sauteed Kale,My Favorite Sauteed Kale is a nutrient-dense o...,"[kale, olive oil, red pepper flakes, garlic cl...",154.2,5.8g,18.9g,8.0g,My Favorite Sauteed Kale,...,3.4,1.8,1.2,0.6,5.8,3.1,0.320405,0.75,0.50,7.4
4,user_01,12569,Hearty Black Beans & Rice,Hearty Black Beans & Rice combines protein-ric...,"[black beans (and liquid), onion, cloves garli...",533.8,11.4g,101.5g,11.2g,Hearty Black Beans & Rice,...,14.1,2.8,8.3,1.6,11.4,2.2,0.266208,0.75,0.25,6.1

In [39]:
print(
    "recommendations without recipe data:",
    merged_df["title_recipe"].isna().sum()
)

recommendations without recipe data: 0

In [40]:
merged_df[
    [
        "title_rec",
        "rec_protein",
        "protein_per_serving [g]",
        "rec_calories",
        "calories_per_serving [cal]"
    ]
].head(20)

,title_rec,rec_protein,protein_per_serving [g],rec_calories,calories_per_serving [cal]
0,Chickpeas With Spinach (Greek),13.3g,13.3,310.2,310.2
1,Refried Beans,17.6g,17.6,307.1,307.1
2,Egyptian Red Lentil Soup,10.3g,10.3,204.5,204.5
3,My Favorite Sauteed Kale,5.8g,5.8,154.2,154.2
4,Hearty Black Beans & Rice,11.4g,11.4,533.8,533.8
5,Black Bean and Corn Salad,6.4g,6.4,159.6,159.6
6,Fried Cabbage,32.8g,32.8,1176.6,1176.6
7,Black Bean and Corn Salad,6.4g,6.4,159.6,159.6
8,Hummus,5.4g,5.4,144.8,144.8
9,Classic Black Beans and Rice,9.4g,9.4,298.4,298.4
10,Comfort Food Beef Stew,37.8g,37.8,411.3,411.3
11,Classic Black Beans and Rice,9.4g,9.4,298.4,298.4
12,Egyptian Red Lentil Soup,10.3g,10.3,204.5,204.5
13,My Favorite Sauteed Kale,5.8g,5.8,154.2,154.2
14,Easy Parmesan Garlic Chicken,28.3g,28.3,171.3,171.3
15,Salsa Chicken,33.1g,33.1,267.5,267.5
16,Chicken Souvlaki,30.4g,30.4,255.8,255.8
17,Tangy Chicken Piccata,26.3g,26.3,204.2,204.2
18,Un-Boiled Chicken,21.1g,21.1,243.8,243.8
19,Dr. Pat's Hot Toddy Cold Remedy,0.1g,0.1,206.7,206.7

### Build analysis table

In [45]:
analysis_rows = []
for block_index, item in enumerate(recommendations):
    for position, rec in enumerate(item["recommendations"], start=1):
        analysis_rows.append({
            **rec,
            "persona_id": item["persona"]["id"],
            "recommendation_position": position,
            "explanation_id": f"block_{block_index + 1:02d}_position_{position:02d}",
        })

explanations_df = pd.DataFrame(analysis_rows)
recipe_lookup = recipes.copy()
persona_lookup = personas_df.rename(columns={"id": "persona_id"}).copy()

#join-key types on copies, leaving source tables unchanged
explanations_df["recipe_id"] = explanations_df["recipe_id"].astype("string").str.strip()
recipe_lookup["recipe_id"] = recipe_lookup["recipe_id"].astype("string").str.strip()
explanations_df["persona_id"] = explanations_df["persona_id"].astype("string").str.strip()
persona_lookup["persona_id"] = persona_lookup["persona_id"].astype("string").str.strip()

assert recipe_lookup["recipe_id"].notna().all()
assert recipe_lookup["recipe_id"].ne("").all()
assert recipe_lookup["recipe_id"].is_unique, "Recipe IDs must be unique before a many-to-one merge."
assert persona_lookup["persona_id"].notna().all()
assert persona_lookup["persona_id"].is_unique

analysis_df = explanations_df.merge(
    recipe_lookup, on="recipe_id", how="left",
    suffixes=("_rec", "_recipe"), validate="many_to_one", indicator="recipe_match"
).merge(
    persona_lookup, on="persona_id", how="left",
    validate="many_to_one", indicator="persona_match"
)

print("analysis table shape:", analysis_df.shape)
print("recommendation rows retained:", len(analysis_df) == len(explanations_df))
display(analysis_df[["explanation_id", "persona_id", "recommendation_position", "recipe_id", "title_rec", "recipe_match", "persona_match"]].head())
display(analysis_df[["recipe_match", "persona_match"]].apply(pd.Series.value_counts, dropna=False))

analysis table shape: (536, 56)
recommendation rows retained: True

,explanation_id,persona_id,recommendation_position,recipe_id,title_rec,recipe_match,persona_match
0,block_01_position_01,user_01,1,81968,Chickpeas With Spinach (Greek),both,both
1,block_01_position_02,user_01,2,10614,Refried Beans,both,both
2,block_01_position_03,user_01,3,94673,Egyptian Red Lentil Soup,both,both
3,block_01_position_04,user_01,4,364252,My Favorite Sauteed Kale,both,both
4,block_01_position_05,user_01,5,12569,Hearty Black Beans & Rice,both,both

            recipe_match  persona_match
both                 536            536
left_only              0              0
right_only             0              0

### Check data quality and recommendation counts

In [46]:
def summarize_empty_values(frame):
    return pd.DataFrame({
        "null": frame.isna().sum(),
        "blank_string": frame.apply(lambda col: col.map(
            lambda x: isinstance(x, str) and not x.strip()
        ).sum()),
        "empty_collection": frame.apply(lambda col: col.map(
            lambda x: isinstance(x, (list, tuple, dict, np.ndarray)) and len(x) == 0
        ).sum()),
    })

for table_name, frame in {"personas": personas_df, "recommendations": explanations_df, "recipes": recipe_lookup}.items():
    print(table_name)
    summary = summarize_empty_values(frame)
    display(summary.loc[summary.sum(axis=1) > 0])

pair_counts = explanations_df.groupby(["persona_id", "recipe_id"], dropna=False).size()
duplicate_pair_count = int((pair_counts > 1).sum())
extra_duplicate_rows = int((pair_counts - 1).clip(lower=0).sum())
print("recommendation rows:", len(explanations_df))
print("unique persona-recipe pairs:", len(pair_counts))
print("pairs appearing more than once:", duplicate_pair_count)
print("extra rows beyond one per pair:", extra_duplicate_rows)

display(explanations_df.groupby("persona_id").size().rename("recommendations_per_persona").describe())
display(personas_df[["profile.age", "profile.height", "profile.weight"]].describe())

display(recipe_lookup[["title", "ingredients_title", "tags"]].head())

personas

,null,blank_string,empty_collection
profile.dietaryProfile.dietaryRestrictions.selected,0,0,8
profile.dietaryProfile.foodAllergies.selected,0,0,32
profile.dietaryProfile.foodAllergies.other,0,35,0
profile.dietaryProfile.healthConditions.selected,0,0,10
profile.dietaryProfile.healthConditions.other,0,29,0

recommendations

Empty DataFrame
Columns: [null, blank_string, empty_collection]
Index: []

recipes

Empty DataFrame
Columns: [null, blank_string, empty_collection]
Index: []

recommendation rows: 536
unique persona-recipe pairs: 484
pairs appearing more than once: 37
extra rows beyond one per pair: 52

count    40.000000
mean     13.400000
std       1.335895
min      10.000000
25%      12.750000
50%      13.500000
75%      14.000000
max      16.000000
Name: recommendations_per_persona, dtype: float64

       profile.age  profile.height  profile.weight
count    40.000000       40.000000       40.000000
mean     37.275000      168.850000       70.625000
std      15.158965       10.489433       14.657959
min       9.000000      132.000000       28.000000
25%      27.000000      162.750000       62.750000
50%      34.500000      170.000000       70.500000
75%      46.500000      176.250000       78.250000
max      71.000000      188.000000      102.000000

,title,ingredients_title,tags
0,My Own Cube Steak and Gravy,"[cubed steak (4-6 pieces), oil, butter, flour,...","[Moderate Calorie, Vegetarian]"
1,Our Secret Sirloin Steak,"[Lea & Perrins Worcestershire Sauce, Lea & Per...","[Moderate Calorie, Vegetarian]"
2,Mile-High Cabbage Pie #5FIX,"[lean beef, coleslaw mix (cabbage and carrots)...",[Moderate Calorie]
3,15 Minute Shrimp Scampi,"[extra virgin olive oil, onion, cloves garlic,...",[Moderate Calorie]
4,Easy Garlic Rice,"[olive oil, onion, garlic cloves, long grain r...",[Moderate Calorie]

#### Measure explanation length

In [47]:
explanation_text = analysis_df["explanation"]
analysis_df["valid_explanation"] = explanation_text.map(
    lambda value: isinstance(value, str) and bool(value.strip())
)
analysis_df["n_chars"] = explanation_text.map(
    lambda value: len(value) if isinstance(value, str) and value.strip() else pd.NA
).astype("Int64")
analysis_df["n_words"] = explanation_text.map(
    lambda value: len(value.split()) if isinstance(value, str) and value.strip() else pd.NA
).astype("Int64")

print("total recommendation rows:", len(analysis_df))
print("valid explanations:", int(analysis_df["valid_explanation"].sum()))
print("blank, missing, or non-text explanations:", int((~analysis_df["valid_explanation"]).sum()))
display(analysis_df[["n_words", "n_chars"]].describe())

persona_length_summary = analysis_df.groupby("persona_id").agg(
    recommendation_count=("explanation_id", "size"),
    valid_explanation_count=("valid_explanation", "sum"),
    mean_words=("n_words", "mean"),
    median_words=("n_words", "median"),
    mean_chars=("n_chars", "mean"),
)
display(persona_length_summary)

total recommendation rows: 536
valid explanations: 536
blank, missing, or non-text explanations: 0

         n_words     n_chars
count      536.0       536.0
mean   34.951493  211.647388
std     5.344005   32.129712
min         23.0       142.0
25%         31.0       190.0
50%         34.0       209.0
75%         38.0       226.0
max         52.0       330.0

,recommendation_count,valid_explanation_count,mean_words,median_words,mean_chars
persona_id,,,,,
user_01,14,14,34.0,34.0,208.214286
user_02,11,11,33.727273,33.0,213.545455
user_03,13,13,36.769231,36.0,215.0
user_04,13,13,46.0,46.0,278.615385
user_05,13,13,32.230769,32.0,189.692308
user_06,14,14,41.928571,41.5,258.642857
user_07,13,13,34.846154,35.0,214.307692
user_08,15,15,31.933333,33.0,200.2
user_09,16,16,35.6875,35.0,218.8125
user_10,14,14,37.142857,36.0,234.428571
user_11,14,14,36.142857,34.5,216.5
user_12,10,10,38.9,38.5,232.9
user_13,13,13,31.384615,31.0,185.692308
user_14,13,13,38.153846,40.0,230.0
user_15,15,15,32.666667,33.0,196.0
user_16,13,13,32.769231,33.0,198.230769
user_17,12,12,37.5,37.0,219.833333
user_18,15,15,32.666667,33.0,198.466667
user_19,13,13,33.384615,33.0,205.0
user_20,12,12,40.5,41.0,251.5
user_21,13,13,37.230769,36.0,219.230769
user_22,15,15,29.666667,30.0,178.066667
user_23,14,14,33.928571,32.5,201.857143
user_24,15,15,31.0,30.0,197.933333
user_25,14,14,35.714286,36.0,209.285714
user_26,14,14,33.428571,33.0,201.928571
user_27,14,14,37.785714,37.0,219.428571
user_28,14,14,35.357143,35.0,209.928571
user_29,12,12,29.25,29.0,184.25
user_30,12,12,33.25,32.5,206.916667
user_31,15,15,36.866667,36.0,222.866667
user_32,14,14,37.214286,36.5,225.357143
user_33,13,13,35.384615,35.0,212.307692
user_34,12,12,32.166667,32.0,198.25
user_35,14,14,33.071429,33.0,201.071429
user_36,11,11,32.090909,32.0,203.818182
user_37,12,12,43.083333,43.0,249.833333
user_38,15,15,29.133333,29.0,177.0
user_39,12,12,28.333333,28.0,168.916667
user_40,15,15,37.733333,37.0,224.8

### Label explanation type and coverage

In [48]:
'''
Mark preference coverage when
the explanation connects a reason to this persona’s stated likes, dislikes, cuisine, or goal.
Mark health justification when
it gives a reason related to health, a diet restriction, an allergy, or a health condition.
'''
annotation_columns = [
    "ingredient_focused", "nutrition_focused", "taste_focused",
    "preference_coverage", "health_justification"
]

annotation_df = analysis_df.loc[
    analysis_df["valid_explanation"],
    [
        "explanation_id", "persona_id", "recommendation_position",
        "recipe_id", "title_rec", "explanation",
        "profile.dietary_goal", "profile.likedIngredients",
        "profile.dislikedIngredients", "profile.favoriteCuisines",
        "profile.dietaryProfile.dietaryRestrictions.selected",
        "profile.dietaryProfile.dietaryRestrictions.other",
        "profile.dietaryProfile.foodAllergies.selected",
        "profile.dietaryProfile.foodAllergies.other",
        "profile.dietaryProfile.healthConditions.selected",
        "profile.dietaryProfile.healthConditions.other",
    ]
].copy()

for column in annotation_columns:
    annotation_df[column] = pd.Series(pd.NA, index=annotation_df.index, dtype="boolean")
annotation_df["label_notes"] = ""

print("Rows requiring labels:", len(annotation_df))
display(annotation_df.sample(min(20, len(annotation_df)), random_state=42))

Rows requiring labels: 536

,explanation_id,persona_id,recommendation_position,recipe_id,title_rec,explanation,profile.dietary_goal,profile.likedIngredients,profile.dislikedIngredients,profile.favoriteCuisines,...,profile.dietaryProfile.foodAllergies.selected,profile.dietaryProfile.foodAllergies.other,profile.dietaryProfile.healthConditions.selected,profile.dietaryProfile.healthConditions.other,ingredient_focused,nutrition_focused,taste_focused,preference_coverage,health_justification,label_notes
117,block_09_position_12,user_09,12,20289,Melt in Your Mouth Banana Bread,Melt in Your Mouth Banana Bread is a delicious...,Energy Boost,"[Oatmeal, Bananas, Chicken breast, Ginger]","[Tomatoes, Coffee]","[American, Korean]",...,[],,[GERD],,<NA>,<NA>,<NA>,<NA>,<NA>,
132,block_10_position_11,user_10,11,31694,Chicken Waldorf Salad,Chicken Waldorf Salad is a refreshing option t...,Maintenance,"[Plain pasta, Chicken nuggets (baked), Apples,...","[Mixed textures (stews), Mushrooms]","[American, Italian]",...,[],,[Autism Spectrum],Sensory processing challenges,<NA>,<NA>,<NA>,<NA>,<NA>,
154,block_12_position_05,user_12,5,40516,Mandarin Salad,Mandarin Salad is a refreshing option that fea...,Weight Loss,"[Rice, Zucchini, Eggs, Strawberries]","[Onion, Garlic]","[Japanese, Mediterranean]",...,[],,[IBS],,<NA>,<NA>,<NA>,<NA>,<NA>,
245,block_19_position_05,user_19,5,118072,Chicken Rice Casserole,Chicken Rice Casserole is a comforting dish th...,Maintenance,"[Dates, Chicken, Rice, Hummus]","[Pork, Cream-based sauces]","[Middle Eastern, North African]",...,[],,[],,<NA>,<NA>,<NA>,<NA>,<NA>,
84,block_07_position_07,user_07,7,119417,Crispy Salmon Cakes With Lemon- Caper Mayonnaise,Crispy Salmon Cakes offer a unique way to enjo...,Maintenance,"[Salmon, Sardines, Olive oil, Tomatoes]","[Shrimp, Crab]","[Mediterranean, Nordic]",...,[Shellfish],,[High Cholesterol],,<NA>,<NA>,<NA>,<NA>,<NA>,
346,block_26_position_10,user_26,10,32918,Chicken Verde,Chicken Verde is a refreshing dish that fits y...,Medical Management,"[Fresh chicken, Rice, Blueberries, Cabbage]","[Sauerkraut, Aged cheese]","[Japanese, American]",...,[],,[Histamine Intolerance],,<NA>,<NA>,<NA>,<NA>,<NA>,
6,block_01_position_07,user_01,7,17107,Fried Cabbage,"Fried Cabbage, while higher in calories, offer...",Muscle Gain,"[Seitan, Lentils, Chickpeas, Hemp seeds]","[Mushrooms, Eggplant]","[Middle Eastern, Indian, Mediterranean]",...,[],,[],,<NA>,<NA>,<NA>,<NA>,<NA>,
478,block_36_position_08,user_36,8,11424,Hummus,Hummus is a nutritious option made from chickp...,Medical Management,"[Unsalted oatmeal, Fresh berries, No-salt bean...","[Canned soups, Fast food]","[American, Mediterranean]",...,[],,[Heart Failure],,<NA>,<NA>,<NA>,<NA>,<NA>,
182,block_14_position_10,user_14,10,105104,"Chicken, Rice, and Spices Bake","Chicken, Rice, and Spices Bake is a hearty dis...",Muscle Gain,"[Chicken, Turkey, Fish, Beans]","[Beef, Pork]","[Thai, Mediterranean]",...,[],Alpha-gal reaction to mammalian products,[Food Allergy],Alpha-gal syndrome,<NA>,<NA>,<NA>,<NA>,<NA>,
55,block_05_position_05,user_05,5,75113,Lemon Rice,Lemon Rice offers a refreshing twist with its ...,Energy Boost,"[Rice, Potatoes, Bananas, Oats (certified GF)]","[Wheat bread, Barley]","[Japanese, Mexican]",...,[],,[Celiac Disease],,<NA>,<NA>,<NA>,<NA>,<NA>,
104,block_08_position_14,user_08,14,33752,French Onion Soup,French Onion Soup is a comforting option that ...,Medical Management,"[Cauliflower, Zucchini, Eggs, Olive oil]","[Bananas, Orange juice]","[American, Mediterranean]",...,[],,[Kidney Disease],CKD stage 3,<NA>,<NA>,<NA>,<NA>,<NA>,
531,block_40_position_11,user_40,11,14788,Kool-Aid Play Dough,This Kool-Aid Play Dough recipe is a fun and l...,Weight Loss,"[Olive oil, Legumes, Fish, Vegetables]","[Sugary soda, White bread]","[Mediterranean, Middle Eastern]",...,[],,"[Prediabetes, Fatty Liver Disease]",NAFLD,<NA>,<NA>,<NA>,<NA>,<NA>,
320,block_24_position_13,user_24,13,14409,Spinach Strawberry Salad,Spinach Strawberry Salad combines spinach with...,Medical Management,"[Salmon, Leafy greens, Fortified plant milk, B...","[Sugary drinks, Processed meats]",[Mediterranean],...,[],,[Lupus],,<NA>,<NA>,<NA>,<NA>,<NA>,
249,block_19_position_09,user_19,9,8594,Fried Rice,"Fried Rice can be a versatile dish, and while ...",Maintenance,"[Dates, Chicken, Rice, Hummus]","[Pork, Cream-based sauces]","[Middle Eastern, North African]",...,[],,[],,<NA>,<NA>,<NA>,<NA>,<NA>,
237,block_18_position_12,user_18,12,25517,Mexican Rice,Mexican Rice is a flavorful vegetarian option ...,Energy Boost,"[Plain white bread, Cheddar, Chicken broth, Ba...","[Spicy foods, Mixed salads]",[American],...,[],,[ARFID],Avoidant/Restrictive Food Intake Disorder,<NA>,<NA>,<NA>,<NA>,<NA>,
469,block_35_position_13,user_35,13,139902,Greek Lemon Chicken Soup,Greek Lemon Chicken Soup is a light and refres...,Muscle Gain,"[Chicken, Sweet potatoes, Avocado, Berries]","[Oatmeal, Scrambled eggs]","[American, Mexican]",...,[Eggs],,[],,<NA>,<NA>,<NA>,<NA>,<NA>,
524,block_40_position_04,user_40,4,50847,Roasted Asparagus,This Roasted Asparagus recipe is another excel...,Weight Loss,"[Olive oil, Legumes, Fish, Vegetables]","[Sugary soda, White bread]","[Mediterranean, Middle Eastern]",...,[],,"[Prediabetes, Fatty Liver Disease]",NAFLD,<NA>,<NA>,<NA>,<NA>,<NA>,
357,block_27_position_07,user_27,7,21623,Chicken Empanadas,"Chicken Empanadas can be a delightful treat, a...",Medical Management,"[Smoothies, Broth, White rice, Egg whites]","[Raw salads, Fried foods]",[American],...,[],,[Gastroparesis],,<NA>,<NA>,<NA>,<NA>,<NA>,
211,block_16_position_11,user_16,11,23425,Baked Pesto Chicken,Baked Pesto Chicken is a delightful dish that ...,Maintenance,"[Chicken, Rice, Yogurt, Blueberries]","[Satay sauces, Peanut oil]","[Mediterranean, American]",...,[Peanuts],Carries epinephrine; avoids may-contain,[Asthma],,<NA>,<NA>,<NA>,<NA>,<NA>,
446,block_34_position_02,user_34,2,26516,Fish Tacos,"Fish Tacos are a delightful way to enjoy fish,...",Medical Management,"[White fish, Rice, Steamed vegetables, Fruit]","[Fried foods, Cream sauces]","[Japanese, Mediterranean]",...,[],,[Pancreatitis],Chronic pancreatitis,<NA>,<NA>,<NA>,<NA>,<NA>,

In [ ]:
#  after done annotation df
if annotation_df[annotation_columns].isna().any().any():
    print("Annotation summary pending: fill every Boolean label, then rerun this cell.")
else:
    label_summary = pd.DataFrame({
        "count": annotation_df[annotation_columns].sum().astype(int),
        "percent": (annotation_df[annotation_columns].mean() * 100).round(1),
    })
    display(label_summary)

    coverage = annotation_df[["preference_coverage", "health_justification"]].astype(bool)
    coverage_summary = pd.Series({
        "both preference and health": int(coverage.all(axis=1).sum()),
        "preference only": int((coverage["preference_coverage"] & ~coverage["health_justification"]).sum()),
        "health only": int((~coverage["preference_coverage"] & coverage["health_justification"]).sum()),
        "neither": int((~coverage.any(axis=1)).sum()),
    }, name="explanation_count")
    display(coverage_summary)